# -*- coding: utf-8 -*-
"""Neural network (gas_turbine)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19WaWkf_DbvcyDJv7lGf2hQ2-mmNrLOFm
"""

# !pip install -U keras-tuner

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras import Sequential
import tensorflow as tf
from tensorflow.keras.layers import Dense
import keras_tuner as kf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from google.colab import files


uploaded = files.upload()

df = pd.read_csv('gas_turbines.csv')

df

df.describe()

df.isnull().sum()

sns.boxplot(df)

sns.pairplot(df)

x = df.drop(columns = ['TEY'])
y = df['TEY']

sc = StandardScaler()

x = sc.fit_transform(x)

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.20, random_state = 53)

ann = Sequential()

ann.add(Dense(units=10, activation = 'relu'))

ann.add(Dense(units=1))

ann.compile(optimizer='adam', loss= 'mse')

ann.fit(xtrain,ytrain, epochs=100, validation_data=(xtest,ytest))

yp = ann.predict(xtest)
yp

from sklearn.metrics import r2_score

r2_score(ytest,yp)

ann.summary()